# python

In [175]:
# except 3 and 8
i = 1 
while i <= 10 :
    if i == 3 or i == 8 :
         i += 1        
         continue 
    print(i,end=" ")
    i += 1
    

1 2 4 5 6 7 9 10 

In [176]:
# unique print
tup = (1,2,3,3,4,44,5,6,"string")
tup1 = set(tup)
tup = tup1
print(tup)

{1, 2, 3, 4, 5, 6, 'string', 44}


In [177]:
# split in 2  parts
li = [1,2,3,4,5,6,7,8,9,10]
mid = len(li)//2
li1 = li[:mid]
li2 = li[mid:]
print(li1)
print(li2)

[1, 2, 3, 4, 5]
[6, 7, 8, 9, 10]


In [178]:
# same element in both list
li = [1,2,3,4,5,6]
li1 = [6,7,8,4,2]
li4 = []
for i in li :
    for j in li1 :
        if i == j :
            li4.append(i)
print(li4)


[2, 4, 6]


In [179]:
# palindrom list
li = [1,2,3,2,1]
li1 = li[::-1]
if li == li1 :
    print("palindrome ")
else :
    print("non palindrome")

palindrome 


In [153]:
# count character
text = "programming"
check = {}

for i in text:
    if i in check:
        check[i] += 1
    else:
        check[i] = 1

print(check)


{'p': 1, 'r': 2, 'o': 1, 'g': 2, 'a': 1, 'm': 2, 'i': 1, 'n': 1}


In [182]:
# replace vowels  with  *
a = "python is programming"
v = "aeiouAEIOU"
b =""
for i in a :
    if i in v :
        b += "*"
        continue
    b += i
b

'pyth*n *s pr*gr*mm*ng'

In [185]:
# check words in string
a = "this is a python"
b = a.split(" ")
print(b)
print("words are ",len(b))
    

['this', 'is', 'a', 'python']
words are  4


In [154]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_namespace__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',


# numpy

In [155]:

import numpy as np 
# array
a = np.arange(1,11)
a 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [156]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [157]:
a = np.linspace(0,1,5)
a

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [158]:
a = np.array([1,2,3,4,5])
print(type(a))
print("dimension is : ",a.ndim)
print("shape is : ",a.shape)

<class 'numpy.ndarray'>
dimension is :  1
shape is :  (5,)


In [159]:
li = [1,2,3,4,5]
print(li)
print(type(li))
ar = np.array(li)
print(type(ar))
print(ar)

[1, 2, 3, 4, 5]
<class 'list'>
<class 'numpy.ndarray'>
[1 2 3 4 5]


In [160]:
import numpy as np

arr = np.array([1, 2, 3, 4])
arr_float = arr.astype(float)

print(arr_float)
print(arr_float.dtype)


[1. 2. 3. 4.]
float64


In [161]:
a = np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [162]:
from numpy import random
 
a = random.randint(40,size=(5))
a

array([31, 23, 36,  4,  6], dtype=int32)

In [163]:
a = np.array([4,5,23,5,67,89,90])
print(a[3])

5


In [164]:
ar = np.array([[1,2,3,4],[4,5,6,7]])
print(ar)
print(ar[1,2])


[[1 2 3 4]
 [4 5 6 7]]
6


In [165]:
a = np.array([1,2,3,4,5,6,7,8])
b = np.where(a % 2 == 0)
b

(array([1, 3, 5, 7]),)

In [166]:
b = a[::-1]
b

array([8, 7, 6, 5, 4, 3, 2, 1])

In [167]:
print("maximum is : ",np.max(a))
print("minimum is : ",np.min(a))

maximum is :  8
minimum is :  1


In [168]:
a = np.array([1,2,76,11,45,3,89,10])
print(a)
for i in range(len(a)) :
    if a[i] > 10 :
       a[i] = 10
print(a)

[ 1  2 76 11 45  3 89 10]
[ 1  2 10 10 10  3 10 10]


In [169]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = np.add(a,b)
c

array([ 7,  9, 11, 13, 15])

In [170]:
b = np.array([1,2,3,4,5])
a = np.full(5,5)
c = np.multiply(a,b)
print("before : ",b)
print("after : ",c)



before :  [1 2 3 4 5]
after :  [ 5 10 15 20 25]


In [171]:
a = random.randint(40,size = (12))
b = a.reshape(3,4)
print(a)
b

[12 15  8 38  8 18 28 20 18 35 32 22]


array([[12, 15,  8, 38],
       [ 8, 18, 28, 20],
       [18, 35, 32, 22]], dtype=int32)

In [172]:
c = a.flatten()
c



array([12, 15,  8, 38,  8, 18, 28, 20, 18, 35, 32, 22], dtype=int32)

In [173]:
a = np.array([[1,2,3,4],[5,6,7,8]])
b = np.sum(a,axis = 1)
b

array([10, 26])

In [174]:
c = np.mean(a,axis = 1)
c

array([2.5, 6.5])